### ISSUE TITLE
案例不错，但是还存在一些问题。

### ISSUE THREAD

**Issue by SunError** [ShanguUncle/UnityChatHololens#2]
1.一分钟音视频测试发现内存上涨明显（增加了200M左右，而且还在不断增加）
2.貌似HoloLens端无法使用更高的分辨率（只能896*504？）

**Comment by ShanguUncle** [comment]
1、开启音视频会有内存上涨，但是稳定在某个值左右的
2、暂时是的，要等官方的sdk及系统更新后才能适配其他分辨率


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ShanguUncle/UnityChatHololens"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月11日(星期五) 下午3:22
收件人:&nbsp;"ShanguUncle/UnityChatHololens"<UnityChatHololens@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ShanguUncle/UnityChatHololens] 案例不错，但是还存在一些问题。 (#2)





 
1.一分钟音视频测试发现内存上涨明显（增加了200M左右，而且还在不断增加）
 2.貌似HoloLens端无法使用更高的分辨率（只能896*504？）

**Comment by ShanguUncle** [comment]
该问题已解决，下载最新v8.1版本
